# Generated by Django 3.1.5 on 2021-01-28 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbicycles',
            options={'ordering': ('titel',)},
        ),
        migrations.AddField(
            model_name='productbicycles',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productbicycles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbicycles',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterIndexTogether(
            name='productbicycles',
            index_together={('id', 'titel_model')},
        ),
    ]
