# Generated by Django 3.1.5 on 2021-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0002_auto_20210129_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_type',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
