# Generated by Django 3.1.5 on 2021-02-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0003_bike_type_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_brand',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
