# Generated by Django 3.1.5 on 2021-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0004_bike_brand_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('categories_bicycles', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
